### PR TITLE
Use Requires for JuMP and Ipopt

### PR DESCRIPTION
**Pull request by xukai92**

### CODE REVIEW

**Comment by juliohm** [comment]
Thanks for the PR. We can even follow a convention where JuMP and solvers are loaded in the files implementing the method. I saw you called the glue file `glue/opt.jl`, maybe add the `using .JuMP` and `using .Ipopt` in the `moment_matching.jl` file itself. I will take a look into the master branch later after you merge the proposed changes here.

**Comment by xukai92** [comment]
> ... maybe add the using .JuMP and using .Ipopt in the moment_matching.jl file itself

I might miss something but you cannot do `using .JuMP` or `using .Ipopt` in `moment_matching.jl` because they are not defined.

**Comment by juliohm** [comment]
I've done it here for example: https://github.com/yurivish/TuringPatterns.jl/blob/master/src/geostats.jl#L5-L6

You can see that GeoStatsBase.jl is not in the dependencies in the Project.toml, but it is made available by Requires.jl

**Comment by xukai92** [comment]
In your example, you do `using` or `import` within the require marco, which is fine. However, our `moment_matching.jl` is always included.

In fact we are doing the same thing in our glue files. We also didn't put them as dependencies (see `deps` section of `Project.toml`).

**Pull request merged**
